FROM adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u192-b12

MAINTAINER Kateryna Shlyakhovetska <shkate@jetbrains.com>

VOLUME /data/teamcity_agent/conf
ENV LANG C.UTF-8
ENV CONFIG_FILE /data/teamcity_agent/conf/buildAgent.properties
LABEL dockerImage.teamcity.version="latest" \
      dockerImage.teamcity.buildNumber="latest"

COPY run-agent.sh /run-agent.sh
COPY run-services.sh /run-services.sh
COPY dist/buildagent /opt/buildagent

RUN apt-get update && \
    apt-get install -y --no-install-recommends sudo && \

    useradd -m buildagent && \
    chmod +x /opt/buildagent/bin/*.sh && \
    chmod +x /run-agent.sh /run-services.sh && sync

CMD ["/run-services.sh"]

EXPOSE 9090
